export const FREEPAID_ERRORCODES = Object.freeze({
    airtimeOKAY:"000",
    airtimePENDING : "001",
    airtimeEMPTYORDER : "100",
    airtimeINVALIDUSER : "101",
    airtimeINVALIDLAST : "102",
    airtimeINVALIDPASS : "103",
    airtimeINVALIDNETWORK : "104",
    airtimeINVALIDSELLVALUE : "105",
    airtimeFUNDSEXCEEDED : "106",
    airtimeOUTOFSTOCK : "107",
    airtimeINVALIDCOUNT : "108",
    airtimeINVALIDREFNO : "109",
    airtimeINVALIDREQUEST : "110",
    airtimeSTILLBUSY : "111",
    airtimeINVALIDORDERNUMBER : "112",
    airtimeINVALIDEXTRA : "113",
    airtimeINTERNAL : "197",
    airtimeTEMPORARY : "198",
    airtimeUNKNOWN : "199",
});